// src/ApprovalGate.jsx
// Human approval gate before committing to repo
import { useState } from 'react'
import { getToken } from './api.js'

const API_BASE = import.meta.env.VITE_API_URL || 'https://api.safecitysentinel.com'

function authHeaders() {
  return { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + getToken() }
}

export default function ApprovalGate({ session, onApprove, onReject, onClose }) {
  const [committing, setCommitting] = useState(false)
  const [committed,  setCommitted]  = useState(null)
  const [error,      setError]      = useState('')
  const [prUrl,      setPrUrl]      = useState('')
  const [repoConfig, setRepoConfig] = useState({
    owner:  session.repoOwner || '',
    repo:   session.repoName  || '',
    branch: 'feat/' + (session.branchName || 'agentpool-session-' + (session.id || '').slice(0,6)),
    base:   'main',
  })

  const files      = session.files      || []
  const testResult = session.testResult || null
  const passed     = testResult ? testResult.passed  : null
  const failed     = testResult ? testResult.failed  : null
  const coverage   = testResult ? testResult.coverage : null

  async function handleCommit() {
    if (!repoConfig.owner || !repoConfig.repo) {
      setError('Please enter GitHub owner and repo')
      return
    }
    setCommitting(true)
    setError('')
    try {
      // 1. Create branch
      const branchRes = await fetch(API_BASE + '/api/git/branch', {
        method: 'POST', headers: authHeaders(),
        body: JSON.stringify({ owner: repoConfig.owner, repo: repoConfig.repo, branch: repoConfig.branch, from: repoConfig.base })
      })
      const branchData = await branchRes.json()
      if (!branchRes.ok) throw new Error(branchData.error || 'Branch creation failed')

      // 2. Commit files
      const commitRes = await fetch(API_BASE + '/api/git/commit', {
        method: 'POST', headers: authHeaders(),
        body: JSON.stringify({
          owner: repoConfig.owner, repo: repoConfig.repo,
          branch: repoConfig.branch, files,
          message: session.commitMessage || 'feat: AgentPool session ' + (session.id || '').slice(0,6),
          sessionId: session.id
        })
      })
      const commitData = await commitRes.json()
      if (!commitRes.ok) throw new Error(commitData.error || 'Commit failed')

      // 3. Open PR
      const prBody = [
        '## AgentPool Session',
        '',
        '**Requirement:** ' + (session.requirement || '').slice(0, 200),
        '',
        '**Files changed:** ' + files.length,
        testResult ? '**Tests:** ' + passed + '/' + testResult.total + ' passing' + (coverage ? ', ' + coverage + '% coverage' : '') : '',
        '',
        '**Session ID:** ' + (session.id || ''),
        '',
        '---',
        '_Generated by AgentPool · SENTINEL-AI_'
      ].filter(Boolean).join('\n')

      const prRes = await fetch(API_BASE + '/api/git/pr', {
        method: 'POST', headers: authHeaders(),
        body: JSON.stringify({
          owner: repoConfig.owner, repo: repoConfig.repo,
          branch: repoConfig.branch, base: repoConfig.base,
          title: session.commitMessage || 'feat: AgentPool session',
          body: prBody
        })
      })
      const prData = await prRes.json()
      if (!prRes.ok) throw new Error(prData.error || 'PR creation failed')

      setPrUrl(prData.prUrl)
      setCommitted(commitData)
      onApprove && onApprove({ ...commitData, prUrl: prData.prUrl })
    } catch(e) {
      setError(e.message)
    }
    setCommitting(false)
  }

  function updateRepo(field, value) {
    setRepoConfig(function(p) { return Object.assign({}, p, { [field]: value }) })
  }

  return (
    <div className="modal-ov" onClick={onClose}>
      <div className="modal approval-modal" style={{ '--ac': '#00ff88', maxWidth: 600 }} onClick={function(e) { e.stopPropagation() }}>
        <div className="modal-hdr">
          <div className="modal-title">
            <span style={{ color: '#00ff88' }}>⬡</span>
            {committed ? 'Committed Successfully' : 'Human Approval Gate'}
          </div>
          <button className="modal-close" onClick={onClose}>✕</button>
        </div>

        <div className="modal-body" style={{ padding: 0 }}>
          {/* Test Results */}
          {testResult && (
            <div className="ag-section" style={{ borderBottom: '1px solid var(--bd)', padding: '12px 16px' }}>
              <div className="ag-section-title">Test Results</div>
              <div className="ag-tests">
                <div className="ag-test-summary">
                  <span style={{ color: '#00ff88' }}>✓ {passed} passing</span>
                  {failed > 0 && <span style={{ color: '#ff4560' }}>✗ {failed} failing</span>}
                  {coverage !== null && <span style={{ color: '#00d4ff' }}>{coverage}% coverage</span>}
                </div>
                {testResult.tests && testResult.tests.map(function(t, i) {
                  return (
                    <div key={i} className="ag-test-row" style={{ color: t.status === 'pass' ? '#00ff88' : t.status === 'fail' ? '#ff4560' : '#ff9500' }}>
                      <span>{t.status === 'pass' ? '✓' : t.status === 'fail' ? '✗' : '–'}</span>
                      <span className="ag-test-name">{t.name}</span>
                      <span style={{ color: 'var(--td)', marginLeft: 'auto' }}>{t.duration}</span>
                    </div>
                  )
                })}
              </div>
            </div>
          )}

          {/* Files to commit */}
          <div className="ag-section" style={{ borderBottom: '1px solid var(--bd)', padding: '12px 16px' }}>
            <div className="ag-section-title">Files to Commit ({files.length})</div>
            <div className="ag-files">
              {files.map(function(f, i) {
                const lines = (f.content || '').split('\n').length
                return (
                  <div key={i} className="ag-file-row">
                    <span style={{ color: '#00ff88' }}>+</span>
                    <span className="ag-file-path">{f.path}</span>
                    <span style={{ color: 'var(--td)', marginLeft: 'auto', fontSize: 9 }}>{lines}L</span>
                  </div>
                )
              })}
              {files.length === 0 && <div style={{ color: 'var(--td)', fontSize: 10 }}>No files generated yet — run the execution pipeline first</div>}
            </div>
          </div>

          {/* Repo config */}
          {!committed && (
            <div className="ag-section" style={{ padding: '12px 16px' }}>
              <div className="ag-section-title">Commit To</div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 8 }}>
                <div>
                  <label className="sg-label">GitHub Owner</label>
                  <input className="sg-input" placeholder="stanwhyte" value={repoConfig.owner} onChange={function(e) { updateRepo('owner', e.target.value) }} />
                </div>
                <div>
                  <label className="sg-label">Repository</label>
                  <input className="sg-input" placeholder="sentinel-vault" value={repoConfig.repo} onChange={function(e) { updateRepo('repo', e.target.value) }} />
                </div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 12 }}>
                <div>
                  <label className="sg-label">Branch Name</label>
                  <input className="sg-input" value={repoConfig.branch} onChange={function(e) { updateRepo('branch', e.target.value) }} />
                </div>
                <div>
                  <label className="sg-label">Base Branch</label>
                  <input className="sg-input" value={repoConfig.base} onChange={function(e) { updateRepo('base', e.target.value) }} />
                </div>
              </div>
              {error && <div style={{ color: '#ff4560', fontSize: 10, marginBottom: 8, padding: '4px 8px', border: '1px solid rgba(255,69,96,.3)' }}>⚠ {error}</div>}
              <div style={{ display: 'flex', gap: 8 }}>
                <button className="ag-approve-btn" onClick={handleCommit} disabled={committing || files.length === 0}>
                  {committing ? '◌ Committing...' : '✓ Approve & Commit'}
                </button>
                <button className="ag-reject-btn" onClick={function() { onReject && onReject(); onClose && onClose() }}>
                  ✗ Reject
                </button>
              </div>
            </div>
          )}

          {/* Success state */}
          {committed && (
            <div className="ag-section" style={{ padding: '16px' }}>
              <div style={{ color: '#00ff88', fontFamily: 'var(--disp)', fontSize: 13, fontWeight: 700, marginBottom: 8 }}>
                ✓ Committed to {repoConfig.owner}/{repoConfig.repo}
              </div>
              <div style={{ fontSize: 10, color: 'var(--td)', marginBottom: 4 }}>Branch: {repoConfig.branch}</div>
              <div style={{ fontSize: 10, color: 'var(--td)', marginBottom: 12 }}>SHA: {(committed.sha || '').slice(0, 12)}</div>
              {prUrl && (
                <a href={prUrl} target="_blank" rel="noreferrer" className="ag-pr-link">
                  → View Pull Request ↗
                </a>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
